{
  "experiment_name": "large_scale_cognitive_test",
  "total_clients": 12,
  "successful_clients": 0,
  "failed_clients": 12,
  "duration_seconds": 60.099143981933594,
  "results": {
    "client_logs": {
      "0": {
        "stdout": "",
        "stderr": "2025-09-05 15:40:55,620 - large_scale_cognitive_test_client_0 - INFO - Starting client 0 with config: {'client_id': 0, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 456, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}\n2025-09-05 15:41:00,403 - large_scale_cognitive_test_client_0 - INFO - Client 0 initialized with 6134 training samples\n2025-09-05 15:41:00,404 - large_scale_cognitive_test_client_0 - INFO - Client 0 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:00,405 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:00,439 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:00,441 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:00,443 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:00,689 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:00,894 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:00,895 - large_scale_cognitive_test_client_0 - ERROR - Client 0 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\n"
      },
      "1": {
        "stdout": "",
        "stderr": "2025-09-05 15:40:56,985 - large_scale_cognitive_test_client_1 - INFO - Starting client 1 with config: {'client_id': 1, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 457, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}\n2025-09-05 15:41:02,137 - large_scale_cognitive_test_client_1 - INFO - Client 1 initialized with 5928 training samples\n2025-09-05 15:41:02,137 - large_scale_cognitive_test_client_1 - INFO - Client 1 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:02,138 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:02,152 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:02,154 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:02,154 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:02,471 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:02,678 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:02,679 - large_scale_cognitive_test_client_1 - ERROR - Client 1 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\n"
      },
      "2": {
        "stdout": "",
        "stderr": "2025-09-05 15:40:59,403 - large_scale_cognitive_test_client_2 - INFO - Starting client 2 with config: {'client_id': 2, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 458, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}\n2025-09-05 15:41:04,152 - large_scale_cognitive_test_client_2 - INFO - Client 2 initialized with 6003 training samples\n2025-09-05 15:41:04,153 - large_scale_cognitive_test_client_2 - INFO - Client 2 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:04,153 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:04,166 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:04,167 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:04,168 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:04,403 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:04,610 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:04,610 - large_scale_cognitive_test_client_2 - ERROR - Client 2 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\n"
      },
      "3": {
        "stdout": "",
        "stderr": "2025-09-05 15:41:02,487 - large_scale_cognitive_test_client_3 - INFO - Starting client 3 with config: {'client_id': 3, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 459, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}\n2025-09-05 15:41:06,309 - large_scale_cognitive_test_client_3 - INFO - Client 3 initialized with 5881 training samples\n2025-09-05 15:41:06,309 - large_scale_cognitive_test_client_3 - INFO - Client 3 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:06,309 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:06,324 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:06,325 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:06,326 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:06,568 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:06,776 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:06,777 - large_scale_cognitive_test_client_3 - ERROR - Client 3 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\n"
      },
      "4": {
        "stdout": "",
        "stderr": "2025-09-05 15:41:09,995 - large_scale_cognitive_test_client_4 - INFO - Starting client 4 with config: {'client_id': 4, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 460, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}\n2025-09-05 15:41:14,060 - large_scale_cognitive_test_client_4 - INFO - Client 4 initialized with 5958 training samples\n2025-09-05 15:41:14,061 - large_scale_cognitive_test_client_4 - INFO - Client 4 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:14,061 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:14,097 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:14,098 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:14,099 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:14,339 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:14,543 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:14,543 - large_scale_cognitive_test_client_4 - ERROR - Client 4 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\n"
      },
      "5": {
        "stdout": "",
        "stderr": "2025-09-05 15:41:11,986 - large_scale_cognitive_test_client_5 - INFO - Starting client 5 with config: {'client_id': 5, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 461, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}\n2025-09-05 15:41:16,577 - large_scale_cognitive_test_client_5 - INFO - Client 5 initialized with 6157 training samples\n2025-09-05 15:41:16,577 - large_scale_cognitive_test_client_5 - INFO - Client 5 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:16,577 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:16,593 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:16,595 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:16,595 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:16,938 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:17,145 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:17,146 - large_scale_cognitive_test_client_5 - ERROR - Client 5 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\n"
      },
      "6": {
        "stdout": "",
        "stderr": "2025-09-05 15:41:14,324 - large_scale_cognitive_test_client_6 - INFO - Starting client 6 with config: {'client_id': 6, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 462, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': False}\n2025-09-05 15:41:18,605 - large_scale_cognitive_test_client_6 - INFO - Client 6 initialized with 5957 training samples\n2025-09-05 15:41:18,605 - large_scale_cognitive_test_client_6 - INFO - Client 6 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:18,605 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:18,621 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:18,622 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:18,622 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:20,961 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:21,168 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:21,169 - large_scale_cognitive_test_client_6 - ERROR - Client 6 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\n"
      },
      "7": {
        "stdout": "",
        "stderr": "2025-09-05 15:41:16,712 - large_scale_cognitive_test_client_7 - INFO - Starting client 7 with config: {'client_id': 7, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 463, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': False}\n2025-09-05 15:41:20,591 - large_scale_cognitive_test_client_7 - INFO - Client 7 initialized with 6176 training samples\n2025-09-05 15:41:20,591 - large_scale_cognitive_test_client_7 - INFO - Client 7 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:20,591 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:20,606 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:20,606 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:20,607 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:20,961 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:21,168 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:21,169 - large_scale_cognitive_test_client_7 - ERROR - Client 7 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\n"
      },
      "8": {
        "stdout": "",
        "stderr": "2025-09-05 15:41:25,022 - large_scale_cognitive_test_client_8 - INFO - Starting client 8 with config: {'client_id': 8, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 464, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': False}\n2025-09-05 15:41:29,166 - large_scale_cognitive_test_client_8 - INFO - Client 8 initialized with 6078 training samples\n2025-09-05 15:41:29,167 - large_scale_cognitive_test_client_8 - INFO - Client 8 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:29,168 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:29,207 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:29,208 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:29,209 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:29,613 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:29,821 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:29,821 - large_scale_cognitive_test_client_8 - ERROR - Client 8 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\n"
      },
      "9": {
        "stdout": "",
        "stderr": "2025-09-05 15:41:26,998 - large_scale_cognitive_test_client_9 - INFO - Starting client 9 with config: {'client_id': 9, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 465, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': False}\n2025-09-05 15:41:31,681 - large_scale_cognitive_test_client_9 - INFO - Client 9 initialized with 6101 training samples\n2025-09-05 15:41:31,682 - large_scale_cognitive_test_client_9 - INFO - Client 9 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:31,682 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:31,700 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:31,701 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:31,702 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:31,947 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:32,155 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:32,155 - large_scale_cognitive_test_client_9 - ERROR - Client 9 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\n"
      },
      "10": {
        "stdout": "",
        "stderr": "2025-09-05 15:41:29,352 - large_scale_cognitive_test_client_10 - INFO - Starting client 10 with config: {'client_id': 10, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 466, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': False}\n2025-09-05 15:41:37,688 - large_scale_cognitive_test_client_10 - INFO - Client 10 initialized with 5930 training samples\n2025-09-05 15:41:37,688 - large_scale_cognitive_test_client_10 - INFO - Client 10 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:37,688 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:37,704 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:37,706 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:37,706 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:37,950 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:38,157 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:38,158 - large_scale_cognitive_test_client_10 - ERROR - Client 10 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"}\"\n>\n"
      },
      "11": {
        "stdout": "",
        "stderr": "2025-09-05 15:41:31,846 - large_scale_cognitive_test_client_11 - INFO - Starting client 11 with config: {'client_id': 11, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 467, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': False}\n2025-09-05 15:41:39,649 - large_scale_cognitive_test_client_11 - INFO - Client 11 initialized with 5955 training samples\n2025-09-05 15:41:39,649 - large_scale_cognitive_test_client_11 - INFO - Client 11 connecting to 20.169.237.127:8080\n\u001b[93mWARNING \u001b[0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:39,649 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.\n\tInstead, use the `flower-supernode` CLI command to start a SuperNode as shown below:\n\n\t\t$ flower-supernode --insecure --superlink='<IP>:<PORT>'\n\n\tTo view all available options, run:\n\n\t\t$ flower-supernode --help\n\n\tUsing `start_client()` is deprecated.\n\n            This is a deprecated feature. It will be removed\n            entirely in future versions of Flower.\n        \n2025-09-05 15:41:39,666 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)\n2025-09-05 15:41:39,667 - flwr - DEBUG - ChannelConnectivity.IDLE\n2025-09-05 15:41:39,668 - flwr - DEBUG - ChannelConnectivity.CONNECTING\n2025-09-05 15:41:39,909 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE\n2025-09-05 15:41:40,112 - flwr - DEBUG - gRPC channel closed\n2025-09-05 15:41:40,113 - large_scale_cognitive_test_client_11 - ERROR - Client 11 failed: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 120, in <module>\n    main()\n    ~~~~^^\n  File \"/Users/hanafemira/development/FL_CognitiveDefence/src/clients/client_runner.py\", line 103, in main\n    fl.client.start_client(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client=fl_client.to_client()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 183, in start_client\n    start_client_internal(\n    ~~~~~~~~~~~~~~~~~~~~~^\n        server_address=server_address,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<10 lines>...\n        max_wait_time=max_wait_time,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/app.py\", line 394, in start_client_internal\n    message = receive()\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py\", line 142, in receive\n    proto = next(server_message_iterator)\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 543, in __next__\n    return self._next()\n           ~~~~~~~~~~^^\n  File \"/Users/hanafemira/development/federated_learning_defense/fl_env/lib/python3.13/site-packages/grpc/_channel.py\", line 969, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14}\"\n>\n"
      }
    },
    "resource_usage": {
      "0": {
        "memory_mb": 383.703125,
        "cpu_percent": 0.0
      },
      "1": {
        "memory_mb": 423.75,
        "cpu_percent": 0.0
      },
      "2": {
        "memory_mb": 221.453125,
        "cpu_percent": 0.0
      },
      "3": {
        "memory_mb": 412.03125,
        "cpu_percent": 0.0
      },
      "4": {
        "memory_mb": 440.0,
        "cpu_percent": 0.0
      },
      "5": {
        "memory_mb": 252.109375,
        "cpu_percent": 0.0
      },
      "6": {
        "memory_mb": 373.09375,
        "cpu_percent": 0.0
      },
      "7": {
        "memory_mb": 336.59375,
        "cpu_percent": 0.0
      },
      "8": {
        "memory_mb": 438.71875,
        "cpu_percent": 0.0
      },
      "9": {
        "memory_mb": 389.984375,
        "cpu_percent": 0.0
      },
      "10": {
        "memory_mb": 501.5625,
        "cpu_percent": 0.0
      },
      "11": {
        "memory_mb": 546.015625,
        "cpu_percent": 0.0
      }
    },
    "status_summary": {
      "0": "failed",
      "1": "failed",
      "2": "failed",
      "3": "failed",
      "4": "failed",
      "5": "failed",
      "6": "failed",
      "7": "failed",
      "8": "failed",
      "9": "failed",
      "10": "failed",
      "11": "failed"
    }
  }
}