2025-09-05 15:32:09,872 - large_scale_cognitive_test_client_5 - INFO - Starting client 5 with config: {'client_id': 5, 'server_address': '0.0.0.0:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 461, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}
2025-09-05 15:32:14,945 - large_scale_cognitive_test_client_5 - INFO - Client 5 initialized with 6157 training samples
2025-09-05 15:32:14,946 - large_scale_cognitive_test_client_5 - INFO - Client 5 connecting to 0.0.0.0:8080
2025-09-05 15:32:14,946 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 15:32:14,959 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 15:32:14,960 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 15:32:14,966 - flwr - DEBUG - gRPC channel closed
2025-09-05 15:32:14,966 - large_scale_cognitive_test_client_5 - ERROR - Client 5 failed: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-09-05 15:38:26,384 - large_scale_cognitive_test_client_5 - INFO - Starting client 5 with config: {'client_id': 5, 'server_address': '0.0.0.0:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 461, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}
2025-09-05 15:38:31,036 - large_scale_cognitive_test_client_5 - INFO - Client 5 initialized with 6157 training samples
2025-09-05 15:38:31,036 - large_scale_cognitive_test_client_5 - INFO - Client 5 connecting to 0.0.0.0:8080
2025-09-05 15:38:31,036 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 15:38:31,052 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 15:38:31,053 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 15:38:31,054 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE
2025-09-05 15:38:31,260 - flwr - DEBUG - gRPC channel closed
2025-09-05 15:38:31,261 - large_scale_cognitive_test_client_5 - ERROR - Client 5 failed: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14}"
>
2025-09-05 15:41:11,986 - large_scale_cognitive_test_client_5 - INFO - Starting client 5 with config: {'client_id': 5, 'server_address': '20.169.237.127:8080', 'experiment_name': 'large_scale_cognitive_test', 'seed': 461, 'batch_size': 32, 'epochs': 2, 'learning_rate': 0.001, 'attack_enabled': True, 'attack_type': 'label_flip', 'attack_intensity': 0.2}
2025-09-05 15:41:16,577 - large_scale_cognitive_test_client_5 - INFO - Client 5 initialized with 6157 training samples
2025-09-05 15:41:16,577 - large_scale_cognitive_test_client_5 - INFO - Client 5 connecting to 20.169.237.127:8080
2025-09-05 15:41:16,577 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 15:41:16,593 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 15:41:16,595 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 15:41:16,595 - flwr - DEBUG - ChannelConnectivity.CONNECTING
2025-09-05 15:41:16,938 - flwr - DEBUG - ChannelConnectivity.TRANSIENT_FAILURE
2025-09-05 15:41:17,145 - flwr - DEBUG - gRPC channel closed
2025-09-05 15:41:17,146 - large_scale_cognitive_test_client_5 - ERROR - Client 5 failed: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:20.169.237.127:8080: Failed to connect to remote host: connect: Connection refused (61)"}"
>
